### ISSUE TITLE
isRoundingError is not limited to 0.1%

### ISSUE THREAD

**Issue by ethers** [0xProject/contracts#98]
`isRoundingError` https://github.com/0xProject/contracts/blob/888d5a02573572240f4c55e03238be603c13c469/contracts/Exchange.sol#L468 states "Checks if rounding error > 0.1%."

Exchange.sol has https://github.com/0xProject/contracts/blob/888d5a02573572240f4c55e03238be603c13c469/contracts/Exchange.sol
```
        if (isRoundingError(filledTakerTokenAmount, order.takerTokenAmount, order.makerTokenAmount)) {
            LogError(ERROR_ROUNDING_ERROR_TOO_LARGE, order.orderHash);
            return 0;
        }
```
Presumably so that the taker's maximum loss is 0.1%.

But if a maker is offering 1000 tokens for 7 of taker's tokens, and a taker submits 1 taker token, then the taker's loss is larger than 0.001... Taker should have received 142.857 tokens and received only 142 tokens...

Fixes to this should include tests: Related #92

**Comment by willwarren89** [comment]
To determine the amount of `makerToken` that `taker` will receive in the case of a partial fill, we must solve for `x = a/b * y` where

- y = the total amount of makerToken offered by Maker for a given order
- b = the total amount of takerToken requested by Maker for a given order
- a = the amount of takerToken that Taker is attempting to sell/fill (`0 <= a/b <= 1`) 
- all values are of type `uint256`

**It follows that**
- integer division will always produce a truncation error when `(ay mod b) != 0`
- absolute truncation is given by remainder `R = (ay mod b)`
- normalized truncation error (as % of partial fill amount) is given by `e = R/x = b (ay mod b)/ay`

**Analysis**
...

**Comment by ethers** [comment]
@willwarren89 Can you please clarify prior comment?  Is your goal `R/x` to be <= 0.001, where `x` is the `floor(a*y / b)` ?  That's my understanding but this doesn't seem to match https://github.com/0xProject/contracts/pull/129/files#diff-e1e51de7476e0cab7ae50ddcbd4c0ff1R105

Is it possible to step back and also focus on the "customer scenario" and give examples of orders that should not go through because of error too large?

Could those tests be added?  More specifically, can the following "boundary" scenarios/tests be added:
```
error of 9/10000, order should not succeed
error of 10/10000, order should succeed
error of 11/10000, order should succeed
```

Also, the "implemented solution" in prior comment probably describes the old buggy implementation? Perhaps remove it or link to the solution it describes.

Thanks

**Comment by abandeali1** [comment]
The total rounding error percentage is equal to `(absolute rounding error of fillMakerTokenAmount)/(total fillMakerTokenAmount without rounding error)`. 

So if the actual amount you were supposed to fill is 4.28, but Solidity rounds down to 4, your rounding error is `(4.28 - 4)/4.28`. More generically, if we want rounding error to be less than .1%, then:

- let x = `(fillTakerTokenAmount*makerTokenAmount)/takerTokenAmount`
- `(x - floor(x))/x <= .001` 

Since decimals cannot be expressed in Solidity, we multiply this expression by 1000. However, the denominator `(fillTakerTokenAmount*makerTokenAmount)/takerTokenAmount` would also have a rounding error, so we multiply both the numerator and denominator by 1000 again. This leaves us with:

- `(1000000x - 1000000*floor(x))/1000x <= 1`
- This is implemented here: https://github.com/0xProject/contracts/pull/129/files#diff-e1e51de7476e0cab7ae50ddcbd4c0ff1R105

This can actually be simplified significantly. We can calculate the remainder R of `(fillTakerTokenAmount*makerTokenAmount)/takerTokenAmount` with `(fillTakerTokenAmount*makerTokenAmount)%takerTokenAmount`. Then the total rounding error percentage can be expressed as `R/(fillTakerTokenAmount*makerTokenAmount) <= .001`. Again, we multiply by 1000, yielding:

- `((fillTakerTokenAmount*makerTokenAmount)%takerTokenAmount)*1000/(fillTakerTokenAmount*makerTokenAmount) <= 1`
- This is implemented here: https://github.com/0xProject/contracts/commit/c1c4befeac352eaa144cc9c2185e618bea505c82
- This is shown to be equivalent to the previous expression here: https://www.wolframalpha.com/input/?i=((a*b%2Fc)+-+floor(a*b%2Fc))+%2F+(a*b%2Fc)+%3D+((a*b)%25c)%2F(a*b)

**Comment by ethers** [comment]
Nice explanations and link to wolfram.  Some of this documentation would be helpful in the function comments (which could link/url to another document with more details).

**Comment by ethers** [comment]
Also, how about this definition of "rounding error"?  If a user is supposed to get 1000 tokens, they may only get 999 tokens.  Any difference more than 1/1000 of the desired order is considered an unacceptable rounding error, and such a trade will be reverted by the 0x protocol to protect users.  This to me is what it sounded like @willwarren89 described by `e = R/x` https://github.com/0xProject/contracts/issues/98#issuecomment-318201997
This definition could lead to a simpler implementation like:
```
function isRoundingError(uint numerator, uint denominator, uint target)
 constant
 returns (bool isError)
{
 uint remainder = mulmod(target, numerator, denominator);
 // fractional error is (remainder / computed_partial_amount)
 // Because it's integer math, compute the reciprocal of the error and compare it to the reciprocal of 
 // the max allowed fractional error.
 return ((remainder != 0) && (1000 > safeDiv( getPartialAmount( numerator, denominator, target), remainder)));
}
```
Goal is not to advocate for any code change at this stage, but just discussion.

**Comment by ethers** [comment]
If we add to the definition: This means when a taker is fulfilling an order that results in less than 1000 tokens, then there must be no rounding errors at all. If a taker is fulfilling an order that results in 10,000 tokens, they can have a shortfall of at most 10 tokens: they may get 9,990 or 9,991 or 9,992...

Looking like the code needs an extra clause:
```
function isRoundingError(uint numerator, uint denominator, uint target)
  constant
  returns (bool isError)
{
  uint remainder = mulmod(target, numerator, denominator);
  if (remainder == 0) return false;

  uint partialAmount = getPartialAmount(numerator, denominator, target);
  // fractional error is (remainder / computed_partial_amount)
  // Because it's integer math, compute the reciprocal of the error and compare it to the reciprocal of 
  // the max allowed fractional error.
  return ((partialAmount < 1000) || (1000 > safeDiv(partialAmount, remainder)));
}
```
